################
# SkyblockPets #
################

Pets:
  '1':
    primary: "&f"
    secondary: "&7"
    type: IRON_GOLEM
    value: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODkwOTFkNzllYTBmNTllZjdlZjk0ZDdiYmE2ZTVmMTdmMmY3ZDQ1NzJjNDRmOTBmNzZjNDgxOWE3MTQifX19"
    name: "&6Iron Golem Pet &7[Level %level%]"
    lore:
      - "&8Support Pet"
      - ""
      - "&7The legendary pet that gives you"
      - "&7a money multiplier for your selling!"
      - ""
      - "&6Level: &fLv %level%"
    price: 50000
    slot: 10
    effects:
      '1':
        type: MONEY_BOOSTER
        amount: 5
        chance: 100
        name: "5% Chance to double your money"
      '2':
        type: MONEY_BOOSTER
        upgrade-price: 25000
        amount: 10
        chance: 80
        name: "10% Chance to double your money"
      '3':
        type: MONEY_BOOSTER
        upgrade-price: 30000
        amount: 15
        chance: 50
        name: "15% Chance to double your money"
      '4':
        type: MONEY_BOOSTER
        upgrade-price: 50000
        amount: 20
        chance: 20
        name: "20% Chance to double your money"